# frozen_string_literal: true

ruby '3.2.4' # facu: 3.3.0

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt'
gem 'rack', '= 3.0.0'
gem 'rake'
gem 'rubocop', '~> 1.66', require: false
gem 'rubycritic'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.4'

group :test, :development do
  gem 'rack-test'
  gem 'rspec'
  gem 'simplecov', require: false
end
