ruby '3.2.4' #facu: 3.3.0

source "https://rubygems.org"

gem 'sinatra'
gem "rack", "= 3.0.0"
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.4'
gem 'rake'
gem 'bcrypt'

group :test, :development do
    gem 'rspec'
    gem 'rack-test'
    gem 'simplecov', require: false
  end